### PR TITLE
Correct wxWidgets GL linkage when using local GLU

### PR DESCRIPTION
**Pull request by bdbcat**

### CODE REVIEW

**Comment by rgleason** [comment]
Dave, this changes pluginconfigure.cmake! 
This is a TP standard cmake file.
Does this mean all plugins need this change?
Is the change "optional" so I can make it without having to rebuild everything?

**Comment by rgleason** [comment]
Later: Had wrong plugin!! Sorry.
Yes, this is exactly right, it is pypilot  master branch that we need to be using!
Sorry.

**Comment by rgleason** [comment]
Later: Had wrong plugin!! Sorry.
Yes, this is exactly right, it is pypilot master branch that we need to be using!
Sorry.

**Comment by bdbcat** [comment]
Is the change "optional"
Yes, required only for plugins using wxGLCanvas.  It seems pypilot is the only affected plugin.
Does no harm to other plugins.
I see no need to rebuild all plugins at this point.  Catch it on the next cycle.

**Comment by rgleason** [comment]
Wonderful. Will do that. Thankyou.

**Pull request merged**
